Update - version code auto increment

diff --git a/.github/workflows/job_firebase_app_distribution.yml b/.github/workflows/job_firebase_app_distribution.yml
--- a/.github/workflows/job_firebase_app_distribution.yml
+++ b/.github/workflows/job_firebase_app_distribution.yml
@@ -41,9 +41,15 @@ jobs:
           id: get_version_code
           working-directory: ./app
           run: |
-              VERSION_CODE=$(grep "versionCode " build.gradle.kts | awk '{print $2}')
-              echo "Current versionCode: $VERSION_CODE"
+            if [ -f "build.gradle.kts" ]; then
+              echo "build.gradle.kts found in root"
+              VERSION_CODE=$(grep "versionCode[[:space:]]*=" build.gradle.kts | awk -F '=' '{print $2}' | sed 's/[^0-9]*//g')
+              echo "Current versionCode (from root/build.gradle.kts): $VERSION_CODE"
               echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
+            else
+              echo "Error: build.gradle.kts not found in root"
+              exit 1
+            fi
 
         - name: Increment versionCode
           id: increment_version_code
